#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_common.sh"

print_source_provenance

if [ "$(host_os)" != "linux" ]; then
  echo "Android builds must run on Linux." >&2
  exit 1
fi

case "$(uname -m)" in
  x86_64 | amd64)
    ;;
  *)
    echo "Android PR builds currently require an x86_64 Linux host because Google's Linux NDK tools are x86_64-only in this SDK package. Current host: $(uname -m)." >&2
    exit 1
    ;;
esac

if [ -z "${ANDROID_HOME:-}" ] || [ ! -d "${ANDROID_HOME}" ]; then
  echo "ANDROID_HOME is not set. Run through 'nix develop .#android'." >&2
  exit 1
fi

if [ -z "${NDK_HOME:-}" ] || [ ! -d "${NDK_HOME}" ]; then
  if [ -d "${ANDROID_HOME}/ndk-bundle" ]; then
    export NDK_HOME="${ANDROID_HOME}/ndk-bundle"
  else
    NDK_HOME="$(find "${ANDROID_HOME}/ndk" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | sort | tail -n 1 || true)"
    export NDK_HOME
  fi
fi

if [ -z "${NDK_HOME:-}" ] || [ ! -d "${NDK_HOME}/toolchains/llvm/prebuilt" ]; then
  echo "Could not find Android NDK under ANDROID_HOME=${ANDROID_HOME}" >&2
  exit 1
fi

install_frontend_deps
configure_sccache
use_pr_environment
configure_reproducible_build_metadata
build_frontend_dist

toolchain_prebuilt="$(
  find "${NDK_HOME}/toolchains/llvm/prebuilt" -mindepth 1 -maxdepth 1 -type d 2>/dev/null \
    | LC_ALL=C sort \
    | head -n 1 || true
)"
if [ -z "${toolchain_prebuilt}" ] || [ ! -d "${toolchain_prebuilt}/bin" ]; then
  echo "Could not find Android NDK LLVM prebuilt toolchain under NDK_HOME=${NDK_HOME}" >&2
  exit 1
fi
export PATH="${toolchain_prebuilt}/bin:${PATH}"

tmp_toolchain_bin="$(mktemp -d)"
cleanup_android_pr() {
  rm -rf "${tmp_toolchain_bin}"
  restore_desktop_goose_cargo_dependencies
}
trap cleanup_android_pr EXIT

ln -sf "${toolchain_prebuilt}/bin/llvm-ranlib" "${tmp_toolchain_bin}/aarch64-linux-android-ranlib"
ln -sf "${toolchain_prebuilt}/bin/llvm-ranlib" "${tmp_toolchain_bin}/armv7a-linux-androideabi-ranlib"
ln -sf "${toolchain_prebuilt}/bin/llvm-ranlib" "${tmp_toolchain_bin}/x86_64-linux-android-ranlib"
ln -sf "${toolchain_prebuilt}/bin/llvm-ranlib" "${tmp_toolchain_bin}/i686-linux-android-ranlib"
export PATH="${tmp_toolchain_bin}:${PATH}"

export AR_aarch64_linux_android="${toolchain_prebuilt}/bin/llvm-ar"
export CC_aarch64_linux_android="${toolchain_prebuilt}/bin/aarch64-linux-android24-clang"
export CXX_aarch64_linux_android="${toolchain_prebuilt}/bin/aarch64-linux-android24-clang++"
export RANLIB_aarch64_linux_android="${toolchain_prebuilt}/bin/llvm-ranlib"

export AR_armv7_linux_androideabi="${toolchain_prebuilt}/bin/llvm-ar"
export CC_armv7_linux_androideabi="${toolchain_prebuilt}/bin/armv7a-linux-androideabi24-clang"
export CXX_armv7_linux_androideabi="${toolchain_prebuilt}/bin/armv7a-linux-androideabi24-clang++"
export RANLIB_armv7_linux_androideabi="${toolchain_prebuilt}/bin/llvm-ranlib"

export AR_x86_64_linux_android="${toolchain_prebuilt}/bin/llvm-ar"
export CC_x86_64_linux_android="${toolchain_prebuilt}/bin/x86_64-linux-android24-clang"
export CXX_x86_64_linux_android="${toolchain_prebuilt}/bin/x86_64-linux-android24-clang++"
export RANLIB_x86_64_linux_android="${toolchain_prebuilt}/bin/llvm-ranlib"

export AR_i686_linux_android="${toolchain_prebuilt}/bin/llvm-ar"
export CC_i686_linux_android="${toolchain_prebuilt}/bin/i686-linux-android24-clang"
export CXX_i686_linux_android="${toolchain_prebuilt}/bin/i686-linux-android24-clang++"
export RANLIB_i686_linux_android="${toolchain_prebuilt}/bin/llvm-ranlib"

android_page_size_flags="-C link-arg=-Wl,-z,max-page-size=16384"
export CARGO_TARGET_AARCH64_LINUX_ANDROID_RUSTFLAGS="${CARGO_TARGET_AARCH64_LINUX_ANDROID_RUSTFLAGS:-${android_page_size_flags}}"
export CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_RUSTFLAGS="${CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_RUSTFLAGS:-${android_page_size_flags}}"
export CARGO_TARGET_I686_LINUX_ANDROID_RUSTFLAGS="${CARGO_TARGET_I686_LINUX_ANDROID_RUSTFLAGS:-${android_page_size_flags}}"
export CARGO_TARGET_X86_64_LINUX_ANDROID_RUSTFLAGS="${CARGO_TARGET_X86_64_LINUX_ANDROID_RUSTFLAGS:-${android_page_size_flags}}"

version="$(jq -r '.version' "${TAURI_DIR}/tauri.conf.json")"
version_code="$(jq -r '.bundle.android.versionCode' "${TAURI_DIR}/tauri.conf.json")"
mkdir -p "${TAURI_DIR}/gen/android/app"
cat > "${TAURI_DIR}/gen/android/app/tauri.properties" << EOF
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
tauri.android.versionName=${version}
tauri.android.versionCode=${version_code}
EOF

cd "${FRONTEND_DIR}"
disable_desktop_goose_cargo_dependencies
bun tauri android build --debug --apk --config '{"build":{"beforeBuildCommand":null}}'

android_artifacts=()
while IFS= read -r -d '' file; do
  android_artifacts+=("${file}")
done < <(find "${TAURI_DIR}/gen/android/app/build/outputs/apk" -type f -name '*.apk' -print0 | LC_ALL=C sort -z)

repro_dir="${TAURI_DIR}/target/reproducibility"
mkdir -p "${repro_dir}"

write_sha256_manifest "${repro_dir}/android-pr-final.sha256" "${android_artifacts[@]}"
print_file_hashes "${android_artifacts[@]}"

payload_manifest="${repro_dir}/android-pr-canonical-payload.sha256"
: > "${payload_manifest}"
for artifact in "${android_artifacts[@]}"; do
  print_zip_payload_hash "${artifact}" "$(repo_relative_path "${artifact}")" | tee -a "${payload_manifest}"
done

verify_frontend_dist_unchanged
