#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_common.sh"

usage() {
  cat >&2 <<'EOF'
usage: release-verification-guide.sh <artifacts-dir> <out.md>

Generates the user-facing release verification guide that is uploaded as a
release asset after CI verifies the release artifacts.
EOF
}

artifacts_dir="${1:-}"
out="${2:-}"

if [ -z "${artifacts_dir}" ] || [ -z "${out}" ] || [ "${artifacts_dir}" = "-h" ] || [ "${artifacts_dir}" = "--help" ]; then
  usage
  exit 2
fi

if [ ! -d "${artifacts_dir}" ]; then
  echo "Artifacts directory does not exist: ${artifacts_dir}" >&2
  exit 1
fi

repo="${GITHUB_REPOSITORY:-OpenSecretCloud/Maple}"
release_tag="${RELEASE_TAG:-${GITHUB_REF_NAME:-}}"
if [ -z "${release_tag}" ]; then
  echo "RELEASE_TAG or GITHUB_REF_NAME is required." >&2
  exit 1
fi

source_commit="$(git -C "${REPO_ROOT}" rev-parse HEAD)"
release_url="https://github.com/${repo}/releases/tag/${release_tag}"
repo_url="https://github.com/${repo}.git"
source_ref="refs/tags/${release_tag}"
clone_dir="maple-${release_tag}"

asset_names=()
while IFS= read -r -d '' file; do
  asset_names+=("$(basename "${file}")")
done < <(find "${artifacts_dir}" -maxdepth 1 -type f -print0 | LC_ALL=C sort -z)

mkdir -p "$(dirname "${out}")"

{
  cat <<EOF
# Maple ${release_tag} Release Verification

This guide was generated by release CI after Maple's release artifact verifier passed.

- Repository: \`${repo}\`
- Release: ${release_url}
- Source ref: \`${source_ref}\`
- Source commit: \`${source_commit}\`

## What The Proofs Cover

The release contains final SHA-256 manifests, canonical payload manifests, Tauri updater signatures, and GitHub artifact attestations. Together they let you check that downloaded bytes match the release, that updater signatures match \`latest.json\`, and that signed Android, macOS, and iOS payloads strip back to the reproducible unsigned build products where that platform supports the check. Windows release proofs cover the final Authenticode-signed NSIS installer, its final Tauri updater signature, and the pinned app-local runtime DLLs used during bundling. Windows verification does not yet canonicalize Authenticode-signed binaries back to an unsigned baseline.

GitHub attestations prove that release CI produced the published bytes for this tag. The Maple verifier then recomputes the local hashes and canonical payload proofs from the files you downloaded.

## Download The Release And Verifier

Install Nix with flakes enabled, then run:

\`\`\`bash
git clone ${repo_url} ${clone_dir}
cd ${clone_dir}
git checkout ${release_tag}
mkdir -p artifacts
gh release download ${release_tag} --repo ${repo} --dir artifacts
\`\`\`

The \`gh release download\` command is the easiest path because it downloads the installers and the matching \`.sha256\` proof files together.

## Verify GitHub Attestations

To verify that each downloaded release asset has a GitHub provenance attestation for this tag:

\`\`\`bash
for file in artifacts/*; do
  gh attestation verify "\${file}" --repo ${repo} --source-ref ${source_ref}
done
\`\`\`

## Verify Reproducibility Proofs

For a broad check of every proof file present in your download:

\`\`\`bash
MAPLE_VERIFY_ALLOW_PLATFORM_SKIPS=1 \\
  nix develop .#ci -c ./scripts/ci/verify-release-artifacts.sh artifacts present
\`\`\`

That command verifies portable hashes and skips host-specific checks that cannot run on your current operating system. For stronger platform checks, run the command for your target platform:

\`\`\`bash
# Linux desktop installers: verifies final hashes, Tauri updater signatures,
# AppImage executable metadata, and .deb executable metadata.
nix develop .#desktop-linux -c ./scripts/ci/verify-release-artifacts.sh artifacts linux

# macOS desktop installers: run on macOS with Xcode selected.
nix develop .#ci -c ./scripts/ci/verify-release-artifacts.sh artifacts macos

# Windows desktop installer: verifies final hashes, pinned runtime DLL proofs,
# and the Tauri updater signature for the signed NSIS installer.
nix develop .#ci -c ./scripts/ci/verify-release-artifacts.sh artifacts windows

# iOS IPA: run on macOS with Xcode selected.
MAPLE_ENFORCE_IOS_SIGNED_REPRODUCIBILITY=1 \\
  nix develop .#ci -c ./scripts/ci/verify-release-artifacts.sh artifacts ios

# Android APK/AAB: verifies final hashes, signed-vs-unsigned canonical payloads,
# and Android signatures when Android SDK tools are available.
MAPLE_REQUIRE_ANDROID_SIGNATURE_VERIFICATION=1 \\
  nix develop .#android -c ./scripts/ci/verify-release-artifacts.sh artifacts android

# Web archive and Tauri updater metadata.
nix develop .#ci -c ./scripts/ci/verify-release-artifacts.sh artifacts web latest-json
\`\`\`

Successful checks print \`verified-...\` lines and exit with status 0. A mismatch exits non-zero and prints the expected and actual digest.

## Release Assets Seen By CI

EOF

  if [ "${#asset_names[@]}" -eq 0 ]; then
    printf 'No release assets were present when this guide was generated.\n'
  else
    for name in "${asset_names[@]}"; do
      printf -- "- \`%s\`\n" "${name}"
    done
  fi

  cat <<'EOF'

If an Apple `*.diff.txt` diagnostic file appears in a release, treat it as a reproducibility failure artifact to inspect. Successful Apple signed-vs-unsigned canonical comparisons should not publish no-op diff files.
EOF
} > "${out}"

printf 'wrote-release-verification-guide  %s\n' "${out}"
