#!/usr/bin/env python3
"""Data and transport boundaries for the independent Rust SDK publisher."""

from __future__ import annotations

from contextlib import redirect_stderr, redirect_stdout
import copy
import gzip
import hashlib
import importlib.util
import io
import json
import os
from pathlib import Path
import struct
import tarfile
import tempfile
import tomllib
import unittest
from unittest.mock import patch
from urllib.error import HTTPError, URLError

SPEC = importlib.util.spec_from_file_location("sdk_crates_upload", Path(__file__).with_name("sdk_crates_upload.py"))
publisher = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(publisher)

# Verbatim normalized Cargo.toml from Cargo 1.89 packaging maple-sdk 3.6.2.
# Source archive SHA256: 6c224c41c00283767e12d40a0c1db0ca928968b26db35111d110eaaecda54792.
NORMALIZED_MANIFEST = '''# THIS FILE IS AUTOMATICALLY GENERATED BY CARGO
#
# When uploading crates to the registry Cargo will automatically
# "normalize" Cargo.toml files for maximal compatibility
# with all versions of Cargo and also rewrite `path` dependencies
# to registry (e.g., crates.io) dependencies.
#
# If you are reading this file be aware that the original Cargo.toml
# will likely look very different (and much more reasonable).
# See Cargo.toml.orig for the original contents.

[package]
edition = "2021"
name = "maple-sdk"
version = "3.6.2"
authors = ["Maple Privacy Labs"]
build = false
autolib = false
autobins = false
autoexamples = false
autotests = false
autobenches = false
description = "Maple Rust SDK for secure AI APIs, encrypted sessions, and Nitro attestation"
homepage = "https://trymaple.ai"
documentation = "https://docs.rs/maple-sdk"
readme = "README.md"
keywords = [
    "maple",
    "ai",
    "encryption",
    "nitro",
    "attestation",
]
categories = [
    "cryptography",
    "api-bindings",
    "web-programming",
]
license = "MIT"
repository = "https://github.com/MaplePrivacyLabs/Maple"

[features]
default = []
mock-attestation = []

[lib]
name = "maple_sdk"
path = "src/lib.rs"

[[example]]
name = "api_usage"
path = "examples/api_usage.rs"

[[example]]
name = "auth_example"
path = "examples/auth_example.rs"

[[test]]
name = "account_management"
path = "tests/account_management.rs"

[[test]]
name = "agent_integration"
path = "tests/agent_integration.rs"

[[test]]
name = "ai_integration"
path = "tests/ai_integration.rs"

[[test]]
name = "api_integration"
path = "tests/api_integration.rs"

[[test]]
name = "api_keys"
path = "tests/api_keys.rs"

[[test]]
name = "attestation"
path = "tests/attestation.rs"

[[test]]
name = "auth_integration"
path = "tests/auth_integration.rs"

[[test]]
name = "bip85_integration"
path = "tests/bip85_integration.rs"

[[test]]
name = "crypto"
path = "tests/crypto.rs"

[[test]]
name = "integration"
path = "tests/integration.rs"

[[test]]
name = "pcr_environment"
path = "tests/pcr_environment.rs"

[[test]]
name = "session"
path = "tests/session.rs"

[[test]]
name = "web_integration"
path = "tests/web_integration.rs"

[dependencies.aes-gcm]
version = "0.10"

[dependencies.anyhow]
version = "1.0"

[dependencies.async-stream]
version = "0.3"

[dependencies.async-trait]
version = "0.1"

[dependencies.base64]
version = "0.22"

[dependencies.bytes]
version = "1.8"

[dependencies.chacha20poly1305]
version = "0.10"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.ciborium]
version = "0.2"

[dependencies.eventsource-stream]
version = "0.2"

[dependencies.futures]
version = "0.3"

[dependencies.hex]
version = "0.4"

[dependencies.hkdf]
version = "0.12"

[dependencies.http]
version = "1.1"

[dependencies.p256]
version = "0.13"
features = [
    "ecdh",
    "pkcs8",
]

[dependencies.percent-encoding]
version = "2.3"

[dependencies.pin-project]
version = "1.1"

[dependencies.reqwest]
version = "0.12.23"
features = [
    "json",
    "stream",
    "rustls-tls",
    "http2",
    "charset",
    "system-proxy",
]
default-features = false

[dependencies.ring]
version = "0.17"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"

[dependencies.sha2]
version = "0.10"

[dependencies.thiserror]
version = "2.0"

[dependencies.tokio]
version = "1.41"
features = ["full"]

[dependencies.tracing]
version = "0.1"

[dependencies.uuid]
version = "1.11"
features = [
    "v4",
    "serde",
]

[dependencies.x25519-dalek]
version = "2.0"
features = ["static_secrets"]

[dependencies.x509-parser]
version = "0.16"

[dependencies.yasna]
version = "0.5"

[dev-dependencies.dotenvy]
version = "0.15.7"

[dev-dependencies.pretty_assertions]
version = "1.4"

[dev-dependencies.tokio-test]
version = "0.4"

[dev-dependencies.tracing-subscriber]
version = "0.3"

[dev-dependencies.wiremock]
version = "0.6"'''


def archive_bytes(entries):
    buffer = io.BytesIO()
    with tarfile.open(fileobj=buffer, mode="w", format=tarfile.PAX_FORMAT) as tar:
        for name, content, kind in entries:
            item = tarfile.TarInfo(name)
            item.type = kind
            item.size = len(content)
            if kind in (tarfile.SYMTYPE, tarfile.LNKTYPE):
                item.linkname = "../../outside"
            tar.addfile(item, io.BytesIO(content))
    return gzip.compress(buffer.getvalue(), mtime=0)


def basic_entries():
    prefix = "maple-sdk-3.6.2/"
    return [(prefix + "Cargo.toml", NORMALIZED_MANIFEST.encode(), tarfile.REGTYPE),
            (prefix + "README.md", "Maple SDK \u2014 fixture\n".encode(), tarfile.REGTYPE),
            (prefix + "src/lib.rs", b"// Not executed by publication.\n", tarfile.REGTYPE)]


class FakeResponse:
    def __init__(self, body=b'{"warnings":{"invalid_categories":[],"invalid_badges":[],"other":[]}}', status=200):
        self.body, self.status = body, status

    def __enter__(self):
        return self

    def __exit__(self, *_):
        pass

    def read(self, limit):
        return self.body[:limit]


class CrateUploadTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.directory = Path(self.temporary.name)
        self.path = self.directory / "package.crate"
        self.path.write_bytes(archive_bytes(basic_entries()))
        self.manifest = tomllib.loads(NORMALIZED_MANIFEST)
        self.files = {"README.md": b"readme", "LICENSE": b"license"}

    def metadata(self):
        return publisher.metadata_from_manifest(self.manifest, self.files, "3.6.2")

    def test_actual_normalized_manifest_encodes_wire_without_changing_archive(self):
        original = self.path.read_bytes()
        metadata, payload, digest = publisher.prepare_upload(self.directory, "3.6.2")
        json_size = struct.unpack_from("<I", payload)[0]
        self.assertEqual(json.loads(payload[4:4 + json_size]), metadata)
        crate_size = struct.unpack_from("<I", payload, 4 + json_size)[0]
        self.assertEqual(crate_size, len(original))
        self.assertEqual(payload[8 + json_size:], original)
        self.assertEqual(digest, hashlib.sha256(original).hexdigest())
        self.assertEqual(metadata["name"], "maple-sdk")
        self.assertEqual(metadata["vers"], "3.6.2")
        self.assertEqual(metadata["readme_file"], "README.md")
        self.assertEqual(metadata["readme"], "Maple SDK \u2014 fixture\n")
        self.assertEqual(metadata["features"], {"default": [], "mock-attestation": []})
        self.assertEqual(len(metadata["deps"]), 34)
        reqwest = next(dep for dep in metadata["deps"] if dep["name"] == "reqwest")
        self.assertEqual(reqwest["version_req"], "0.12.23")
        self.assertFalse(reqwest["default_features"])
        self.assertEqual(reqwest["features"], ["json", "stream", "rustls-tls", "http2", "charset", "system-proxy"])
        self.assertEqual(sum(dep["kind"] == "dev" for dep in metadata["deps"]), 5)

    def test_target_renamed_optional_dependency_and_namespaced_features(self):
        self.manifest["target"] = {'cfg(target_os = "windows")': {"build-dependencies": {
            "renamed": {"package": "upstream", "version": ">=1.2, <2", "optional": True,
                        "default-features": False, "features": ["feature"]}}}}
        self.manifest["features"]["extra"] = ["dep:renamed", "renamed?/feature"]
        dep = self.metadata()["deps"][-1]
        self.assertEqual(dep, {"name": "upstream", "explicit_name_in_toml": "renamed",
                              "version_req": ">=1.2, <2", "optional": True, "default_features": False,
                              "features": ["feature"], "target": 'cfg(target_os = "windows")',
                              "registry": None, "kind": "build"})
        self.assertEqual(self.metadata()["features"]["extra"], ["dep:renamed", "renamed?/feature"])

    def test_manifest_metadata_and_license_file(self):
        self.manifest["package"].update({"license-file": "LICENSE", "rust-version": "1.89",
                                         "links": "native-library", "publish": ["crates-io"]})
        self.manifest["badges"] = {"maintenance": {"status": "actively-developed"}}
        metadata = self.metadata()
        self.assertEqual(metadata["rust_version"], "1.89")
        self.assertEqual(metadata["license_file"], "LICENSE")
        self.assertEqual(metadata["links"], "native-library")
        self.assertEqual(metadata["badges"], self.manifest["badges"])
        self.assertEqual(metadata["authors"], ["Maple Privacy Labs"])
        self.assertEqual(metadata["documentation"], "https://docs.rs/maple-sdk")

    def test_disabled_readme_and_missing_readme_license_reject(self):
        self.manifest["package"]["readme"] = False
        self.assertIsNone(self.metadata()["readme"])
        self.manifest["package"]["readme"] = "missing"
        with self.assertRaises(publisher.Rejected):
            self.metadata()
        self.manifest["package"]["readme"] = False
        self.manifest["package"]["license-file"] = "missing"
        with self.assertRaises(publisher.Rejected):
            self.metadata()

    def test_unrecognized_dependency_sources_and_unstable_forms_reject(self):
        for key, value in {"git": "https://example.invalid", "path": "../other", "workspace": True,
                           "registry": "other", "registry-index": "https://example.invalid",
                           "artifact": "bin", "lib": True, "default_features": False}.items():
            with self.subTest(key=key):
                manifest = copy.deepcopy(self.manifest)
                manifest["dependencies"]["reqwest"][key] = value
                with self.assertRaises(publisher.Rejected):
                    publisher.metadata_from_manifest(manifest, self.files, "3.6.2")
        for key in ("workspace", "patch", "replace", "cargo-features"):
            manifest = dict(self.manifest, **{key: {}})
            with self.subTest(key=key), self.assertRaises(publisher.Rejected):
                publisher.metadata_from_manifest(manifest, self.files, "3.6.2")

    def test_identity_and_publishing_restrictions_fail_closed(self):
        for key, value in (("name", "other"), ("version", "3.6.3"), ("repository", "https://example.invalid"),
                           ("publish", False), ("publish", []), ("publish", ["other"]), ("build", "build.rs")):
            manifest = copy.deepcopy(self.manifest)
            manifest["package"][key] = value
            with self.subTest(key=key, value=value), self.assertRaises(publisher.Rejected):
                publisher.metadata_from_manifest(manifest, self.files, "3.6.2")

    def test_no_prereleases_or_ambiguous_version_inputs(self):
        for version in ("3.6.2-alpha.1", "v3.6.2", "3.6.02", "3.6", "3.6.2+meta", "../3.6.2", "3.6.2\n"):
            with self.subTest(version=version), self.assertRaises(publisher.Rejected):
                publisher.prepare_upload(self.directory, version)

    def test_tar_paths_types_duplicates_and_roots_reject(self):
        bad_entries = [("/absolute", tarfile.REGTYPE), ("maple-sdk-3.6.2/../outside", tarfile.REGTYPE),
                       ("maple-sdk-3.6.2//double", tarfile.REGTYPE), ("maple-sdk-3.6.2/./dot", tarfile.REGTYPE),
                       ("maple-sdk-3.6.2/a\\b", tarfile.REGTYPE), ("maple-sdk-3.6.2/new\nline", tarfile.REGTYPE),
                       ("other-3.6.2/file", tarfile.REGTYPE), ("maple-sdk-3.6.2/link", tarfile.SYMTYPE),
                       ("maple-sdk-3.6.2/link", tarfile.LNKTYPE), ("maple-sdk-3.6.2/dir", tarfile.DIRTYPE),
                       ("maple-sdk-3.6.2/README.md", tarfile.REGTYPE)]
        for name, kind in bad_entries:
            self.path.write_bytes(archive_bytes(basic_entries() + [(name, b"", kind)]))
            with self.subTest(name=name, kind=kind), self.assertRaises(publisher.Rejected):
                publisher.prepare_upload(self.directory, "3.6.2")

    def test_archive_symlink_and_compression_size_limits(self):
        target = self.directory / "elsewhere.crate"
        self.path.rename(target)
        self.path.symlink_to(target)
        with self.assertRaises(publisher.Rejected):
            publisher.prepare_upload(self.directory, "3.6.2")
        self.path.unlink()
        self.path.write_bytes(target.read_bytes())
        with patch.object(publisher, "MAX_ARCHIVE", 16), self.assertRaises(publisher.Rejected):
            publisher.prepare_upload(self.directory, "3.6.2")
        with patch.object(publisher, "MAX_UNPACKED", 16), self.assertRaises(publisher.Rejected):
            publisher.prepare_upload(self.directory, "3.6.2")
        with patch.object(publisher, "MAX_MEMBERS", 2), self.assertRaises(publisher.Rejected):
            publisher.prepare_upload(self.directory, "3.6.2")

    def test_validate_only_does_not_read_credentials_or_open_network(self):
        output = io.StringIO()
        with patch.object(publisher.os, "environ", {}), patch.object(publisher, "upload") as upload:
            with redirect_stdout(output):
                status = publisher.main(["--directory", str(self.directory), "--version", "3.6.2", "--validate-only"])
        self.assertEqual(status, 0)
        self.assertEqual(json.loads(output.getvalue())["status"], "validated")
        upload.assert_not_called()

    def test_upload_is_one_fixed_https_put_of_exact_bytes(self):
        _, payload, _ = publisher.prepare_upload(self.directory, "3.6.2")
        with patch.object(publisher, "build_opener") as build:
            build.return_value.open.return_value = FakeResponse()
            self.assertEqual(publisher.upload(payload, "synthetic-fixture-token"), 0)
        request = build.return_value.open.call_args.args[0]
        self.assertEqual(request.full_url, "https://crates.io/api/v1/crates/new")
        self.assertEqual(request.method, "PUT")
        self.assertEqual(request.data, payload)
        self.assertEqual(request.get_header("Authorization"), "synthetic-fixture-token")
        self.assertEqual(request.get_header("Content-type"), "application/octet-stream")
        build.return_value.open.assert_called_once()
        self.assertEqual(build.call_args.args[0].proxies, {})
        self.assertIsInstance(build.call_args.args[1], publisher.NoRedirect)
        self.assertIsNone(build.call_args.args[1].redirect_request(None, None, 307, "", {}, "https://elsewhere.invalid"))

    def test_no_retry_or_secret_reflection_on_network_errors(self):
        marker = "synthetic-secret-that-must-not-appear"
        for error in (HTTPError("https://elsewhere.invalid/" + marker, 307, marker,
                                {"Location": "https://elsewhere.invalid/" + marker}, io.BytesIO(marker.encode())),
                      HTTPError("https://crates.io/", 403, marker, {}, io.BytesIO(marker.encode())),
                      URLError(marker), TimeoutError(marker)):
            with self.subTest(error=type(error).__name__), patch.object(publisher, "build_opener") as build:
                build.return_value.open.side_effect = error
                with self.assertRaises(publisher.UploadUnconfirmed) as caught:
                    publisher.upload(b"payload", marker)
                self.assertNotIn(marker, str(caught.exception))
                self.assertNotIn("elsewhere", str(caught.exception))
                build.return_value.open.assert_called_once()

    def test_error_bodies_malformed_and_oversized_success_are_not_success(self):
        marker = "synthetic-response-secret"
        for body in (json.dumps({"errors": [{"detail": marker}]}).encode(), marker.encode(), b"[]",
                     b'{"warnings":42}', b" " * (publisher.MAX_RESPONSE + 1)):
            with self.subTest(size=len(body)), patch.object(publisher, "build_opener") as build:
                build.return_value.open.return_value = FakeResponse(body)
                with self.assertRaises(publisher.UploadUnconfirmed) as caught:
                    publisher.upload(b"payload", marker)
                self.assertNotIn(marker, str(caught.exception))
                build.return_value.open.assert_called_once()

    def test_credential_header_injection_fails_before_network(self):
        for token in ("", "token\nInjected: yes", "token\r", "token\u0080", "x" * 4097):
            with patch.object(publisher, "build_opener") as build, self.assertRaises(publisher.Rejected):
                publisher.upload(b"payload", token)
            build.assert_not_called()

    def test_cli_never_prints_local_parser_or_network_error_content(self):
        marker = "synthetic-input-secret"
        self.path.write_bytes(archive_bytes([(name, marker.encode() if name.endswith("Cargo.toml") else content, kind)
                                             for name, content, kind in basic_entries()]))
        output = io.StringIO()
        with redirect_stderr(output):
            self.assertEqual(publisher.main(["--directory", str(self.directory), "--version", "3.6.2"]), 1)
        self.assertNotIn(marker, output.getvalue())
        self.assertNotIn(str(self.directory), output.getvalue())


if __name__ == "__main__":
    unittest.main()
