#!/bin/bash
# Generate .cargo/config.toml for iOS ONNX Runtime linking
# This script creates the config with absolute paths based on the current directory

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TAURI_DIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(cd "${TAURI_DIR}/../.." && pwd)"
CARGO_DIR="${TAURI_DIR}/.cargo"
CONFIG_FILE="${CARGO_DIR}/config.toml"
XCFRAMEWORK_DIR="${TAURI_DIR}/onnxruntime-ios/onnxruntime.xcframework"
CARGO_HOME_DIR="${CARGO_HOME:-${HOME:-}/.cargo}"
RUSTUP_HOME_DIR="${RUSTUP_HOME:-${HOME:-}/.rustup}"
PATH_PREFIX_MAP_FLAGS="-ffile-prefix-map=${REPO_ROOT}=/maple -fmacro-prefix-map=${REPO_ROOT}=/maple -fdebug-prefix-map=${REPO_ROOT}=/maple -ffile-prefix-map=${CARGO_HOME_DIR}=/cargo -fmacro-prefix-map=${CARGO_HOME_DIR}=/cargo -fdebug-prefix-map=${CARGO_HOME_DIR}=/cargo -ffile-prefix-map=${RUSTUP_HOME_DIR}=/rustup -fmacro-prefix-map=${RUSTUP_HOME_DIR}=/rustup -fdebug-prefix-map=${RUSTUP_HOME_DIR}=/rustup"

# Check if xcframework exists
if [ ! -d "$XCFRAMEWORK_DIR" ]; then
    echo "Error: ONNX Runtime xcframework not found at: $XCFRAMEWORK_DIR"
    echo "Run ./scripts/build-ios-onnxruntime-all.sh first"
    exit 1
fi

# Check for required libraries
if [ ! -f "${XCFRAMEWORK_DIR}/ios-arm64/libonnxruntime.a" ]; then
    echo "Error: Device library not found. Build ONNX Runtime first."
    exit 1
fi

mkdir -p "$CARGO_DIR"

echo "Generating ${CONFIG_FILE}..."

cat > "$CONFIG_FILE" << EOF
# Auto-generated cargo config for iOS ONNX Runtime linking
# Generated by: scripts/setup-ios-cargo-config.sh
# Regenerate with: ./scripts/setup-ios-cargo-config.sh

[build]
rustflags = [
  "--remap-path-prefix=${REPO_ROOT}=/maple",
  "--remap-path-prefix=${CARGO_HOME_DIR}=/cargo",
  "--remap-path-prefix=${RUSTUP_HOME_DIR}=/rustup",
]

[env]
CFLAGS = { value = "${PATH_PREFIX_MAP_FLAGS}", force = true }
CXXFLAGS = { value = "${PATH_PREFIX_MAP_FLAGS}", force = true }
OBJCFLAGS = { value = "${PATH_PREFIX_MAP_FLAGS}", force = true }
OBJCXXFLAGS = { value = "${PATH_PREFIX_MAP_FLAGS}", force = true }
CMAKE_C_FLAGS = { value = "${PATH_PREFIX_MAP_FLAGS}", force = true }
CMAKE_CXX_FLAGS = { value = "${PATH_PREFIX_MAP_FLAGS}", force = true }
CMAKE_OBJC_FLAGS = { value = "${PATH_PREFIX_MAP_FLAGS}", force = true }
CMAKE_OBJCXX_FLAGS = { value = "${PATH_PREFIX_MAP_FLAGS}", force = true }
CFLAGS_aarch64_apple_ios = { value = "${PATH_PREFIX_MAP_FLAGS}", force = true }
CXXFLAGS_aarch64_apple_ios = { value = "${PATH_PREFIX_MAP_FLAGS}", force = true }
CFLAGS_aarch64_apple_ios_sim = { value = "${PATH_PREFIX_MAP_FLAGS}", force = true }
CXXFLAGS_aarch64_apple_ios_sim = { value = "${PATH_PREFIX_MAP_FLAGS}", force = true }

[target.aarch64-apple-ios.onnxruntime]
rustc-link-search = ["${XCFRAMEWORK_DIR}/ios-arm64"]
rustc-link-lib = ["static=onnxruntime", "c++"]

[target.aarch64-apple-ios-sim.onnxruntime]
rustc-link-search = ["${XCFRAMEWORK_DIR}/ios-arm64-simulator"]
rustc-link-lib = ["static=onnxruntime", "c++"]
EOF

echo "Created: $CONFIG_FILE"
echo ""
echo "Paths configured:"
echo "  Device:    ${XCFRAMEWORK_DIR}/ios-arm64"
echo "  Simulator: ${XCFRAMEWORK_DIR}/ios-arm64-simulator"

# Verify simulator library exists (warn if not)
if [ ! -f "${XCFRAMEWORK_DIR}/ios-arm64-simulator/libonnxruntime.a" ]; then
    echo ""
    echo "Warning: Simulator library not found!"
    echo "Device builds will work, but simulator builds will fail."
    echo "Run ./scripts/build-ios-onnxruntime-all.sh to build both."
fi
