#!/bin/bash
# Generate .cargo/config.toml for iOS ONNX Runtime linking
# This script creates the config with absolute paths based on the current directory

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TAURI_DIR="$(dirname "$SCRIPT_DIR")"
CARGO_DIR="${TAURI_DIR}/.cargo"
CONFIG_FILE="${CARGO_DIR}/config.toml"
XCFRAMEWORK_DIR="${TAURI_DIR}/onnxruntime-ios/onnxruntime.xcframework"

# Check if xcframework exists
if [ ! -d "$XCFRAMEWORK_DIR" ]; then
    echo "Error: ONNX Runtime xcframework not found at: $XCFRAMEWORK_DIR"
    echo "Run ./scripts/build-ios-onnxruntime-all.sh first"
    exit 1
fi

# Check for required libraries
if [ ! -f "${XCFRAMEWORK_DIR}/ios-arm64/libonnxruntime.a" ]; then
    echo "Error: Device library not found. Build ONNX Runtime first."
    exit 1
fi

mkdir -p "$CARGO_DIR"

echo "Generating ${CONFIG_FILE}..."

cat > "$CONFIG_FILE" << EOF
# Auto-generated cargo config for iOS ONNX Runtime linking
# Generated by: scripts/setup-ios-cargo-config.sh
# Regenerate with: ./scripts/setup-ios-cargo-config.sh

[target.aarch64-apple-ios.onnxruntime]
rustc-link-search = ["${XCFRAMEWORK_DIR}/ios-arm64"]
rustc-link-lib = ["static=onnxruntime"]

[target.aarch64-apple-ios-sim.onnxruntime]
rustc-link-search = ["${XCFRAMEWORK_DIR}/ios-arm64-simulator"]
rustc-link-lib = ["static=onnxruntime"]

[env]
ORT_LIB_LOCATION = "${XCFRAMEWORK_DIR}/ios-arm64"
EOF

echo "Created: $CONFIG_FILE"
echo ""
echo "Paths configured:"
echo "  Device:    ${XCFRAMEWORK_DIR}/ios-arm64"
echo "  Simulator: ${XCFRAMEWORK_DIR}/ios-arm64-simulator"

# Verify simulator library exists (warn if not)
if [ ! -f "${XCFRAMEWORK_DIR}/ios-arm64-simulator/libonnxruntime.a" ]; then
    echo ""
    echo "Warning: Simulator library not found!"
    echo "Device builds will work, but simulator builds will fail."
    echo "Run ./scripts/build-ios-onnxruntime-all.sh to build both."
fi
