name: Rust Unit Tests

permissions:
  contents: read

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rust-tests:
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # was v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # was v22
        with:
          github-token: ""

      - name: Cache sccache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # was v4
        with:
          path: ~/.cache/sccache
          key: ${{ runner.os }}-sccache-rust-tests-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-sccache-rust-tests-
            ${{ runner.os }}-sccache-

      - name: Run Rust unit tests
        run: nix develop .#ci -c ./scripts/ci/rust.sh

      - name: Show sccache stats
        if: always()
        run: nix develop .#ci -c sccache --show-stats
